# ====================================
# COMMON CONFIGURATION (All Profiles)
# ====================================
spring.application.name=ecomdemo

# Active Profile (dev, prod)
spring.profiles.active=${SPRING_PROFILE:dev}

# --- DATABASE DRIVER ---
spring.datasource.driver-class-name=org.postgresql.Driver

# --- FILE UPLOAD ---
spring.web.resources.static-locations=file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- JWT Configuration ---
jwt.secret=${JWT_SECRET:YourBase64EncodedSecretKeyHere256BitsMinimumRequiredForHS256Algorithm}
jwt.expiration=86400000